name: Run One With Name Script

on:
  workflow_dispatch:
    inputs:
      argument:
        description: 'IGDTUW, DTU, IP, IIITD, NSUT'
        required: true

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script with argument
      run: python processOne.py ${{ github.event.inputs.argument }}

    - name: Commit changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"
        git pull
        git add .
        git commit -m "Update Data"
        git push
